# Generated by Django 3.2.16 on 2024-12-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following_user',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_user_follower'),
        ),
    ]
