# Generated by Django 3.2.16 on 2024-12-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following_user',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('following', 'follower'), name='unique_following_follower'),
        ),
    ]
