# Generated by Django 3.2.16 on 2024-12-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20241211_1332'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_follower',
        ),
    ]
